# Examen Python 

### Nombre: Eduardo Carrion


Crear un vector de ceros de tamaño 10

In [1]:
import numpy as np
vector1 = np.zeros(10)
print(vector1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [5]:
vector2 = np.zeros(10)
vector2[4] = 1
print(vector2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc

In [8]:
vector3 = np.arange(50)
print(vector3)
vector3 = vector3[::-1]
print(vector3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Crear una matriz de 3 x 3 con valores del cero al 8

In [11]:
vector4 = np.arange(9).reshape(3,3)
print(vector4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



Encontrar los indices que no sean cero en un arreglo

import numpy as np

arreglo = [1,2,0,0,4,0]


In [23]:
arreglo = np.array([1,2,0,0,4,0])
np.where(arreglo == 0)

(array([2, 3, 5]),)

Crear una matriz de identidad 3 x 3

In [26]:
indentidad = np.eye(3)
print(indentidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Crear una matriz 3 x 3 x 3 con valores randomicos

In [35]:
matriz_random = np.random.randint(32, size=(3, 3, 3))
print(matriz_random)

[[[19  0 13]
  [25 18  0]
  [26 22 19]]

 [[18 11  1]
  [27  2  4]
  [20 14  9]]

 [[20 17 10]
  [13  1 28]
  [ 9  4  2]]]


 Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [46]:
matriz_random2 = np.random.randint(200, size=(10, 10))
print(matriz_random2)
print(np.amin(matriz_random2))
print(np.amax(matriz_random2))

[[ 11  56 188  91  85 169 160 103  44  50]
 [ 88 135 155  16 159  15 138 190  31 141]
 [147 130  71 163 106  88 143  74  78 153]
 [ 23  35  81 116 140  21   0 194 192  27]
 [196  36  87 103 187  58  52  82  58 145]
 [ 52 184  94 184 187 195 110 148 107   6]
 [ 41 142   9 122  32  42 140 180 122 135]
 [194 176   3  40  76  30 103   9 191  10]
 [ 59 172  78  12  35 199 173   6   0  22]
 [107  19  86  86 117 186  83 129 130   9]]
0
199


Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [ ]:
from scipy import ndimage
from scipy import misc

mapache = misc.face()


¿Como crear una serie de una lista, diccionario o arreglo?

import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')

myarr = np.arange(26)

mydict = dict(zip(mylist, myarr))

In [50]:
import pandas as pd
from pandas import Series, DataFrame



mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))


series_a = pd.Series(mylist)

series_b = pd.Series(myarr)

series_c = pd.Series(mydict)

print(series_a)
print(series_b)
print(series_c)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


¿Como convertir el indice de una serie en una columna de un DataFrame?

mylist = list('abcedfghijklmnopqrstuvwxyz')

myarr = np.arange(26)

mydict = dict(zip(mylist, myarr))

ser = pd.Series(mydict) 

#Transformar la serie en dataframe y hacer una columna indice

In [55]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser = pd.Series(mydict) 

df1 = pd.DataFrame(ser)
print(df1)

    0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25


¿Como combinar varias series para hacer un DataFrame?

import numpy as np

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser2 = pd.Series(np.arange(26))

In [64]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df2 = pd.DataFrame(pd.concat([ser1, ser2]))

print(df2)

     0
0    a
1    b
2    c
3    e
4    d
5    f
6    g
7    h
8    i
9    j
10   k
11   l
12   m
13   n
14   o
15   p
16   q
17   r
18   s
19   t
20   u
21   v
22   w
23   x
24   y
25   z
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23
24  24
25  25


¿Como obtener los items que esten en una serie A y no en una serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])

ser2 = pd.Series([4, 5, 6, 7, 8])

In [69]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

print(ser1.isin(ser2))


0    False
1    False
2    False
3     True
4     True
dtype: bool


 ¿Como obtener los items que no son comunes en una serie A y serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])

ser2 = pd.Series([4, 5, 6, 7, 8])


¿Como obtener el numero de veces que se repite un valor en una serie?

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

np.random.RandomState(100)

ser = pd.Series(np.random.randint(1, 5, [12]))

¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?

ser = pd.Series(np.random.randint(1, 10, 35))

shape(7,5)

¿Como importar solo columnas especificas de un archivo csv?

https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.

In [ ]:
import os

path = "/home/dev-11/Documents/Github/py-eguez-sarzosa-vicente-adrian/03 - Pandas/data/artwork_data.csv"
