In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0, 30, 45, 60, 90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [4]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [17]:
numero_random = np.random.randint(11) #[0 , 11[
numero_random

3

In [18]:
numero_random_negativo = np.random.randint(-9 , 2) #[-9 , 2[
numero_random_negativo

-6

In [20]:
arreglo_random = np.random.randint(10, 20, 8)
arreglo_random

array([17, 19, 18, 15, 16, 16, 13, 16])

In [24]:
np.random.rand(9)    #9 elementos
np.random.rand(3,2)  #6 elementos (3x2 dimensiones)

array([[0.90333799, 0.34951923],
       [0.04837013, 0.20766932],
       [0.51529006, 0.00813945]])

In [27]:
np.average(arreglo_random)

16.25

In [28]:
np.mean(arreglo_random) 

16.25

In [29]:
np.median(arreglo_random)

16.0

In [30]:
np.std(arreglo_random) #desviación estandar

1.713913650100261

In [31]:
np.var(arreglo_random)  #varianza

2.9375

In [32]:
arreglo_random.mean()

16.25